project:
  type: website
  output-dir: docs

website:
  site-url: https://hc-sc.github.io/tdu-rph/
  title: "R for Public Health"

  navbar:
    pinned: true
    background: primary
    search: true
    left:
      - text: "Module 1"
        href: module01.html
      - text: "Module 2"
        href: module02.html
      - text: "Module 3"
        href: module03.html
      - text: "Module 4"
        href: module04.html

format:
  html:
    theme: sketchy
    toc: true
    toc-location: right
    toc-depth: 4
    css: temp_styles.css
  docx: default


execute:
  freeze: auto